apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: huarui-user
  namespace: local
spec:
  replicas: 1
  template:
    metadata:
     labels:
       app: huarui-user
    spec:
     containers:
     - name: huarui-user
       image: c568254965/huarui_user:v1.0
       tty: true
       ports:
       - containerPort: 6821
